DROP DATABASE IF EXISTS `Acme-Tender`;
CREATE DATABASE `Acme-Tender`;

USE `Acme-Tender`;

GRANT SELECT, INSERT, UPDATE, DELETE 
  ON `Acme-Tender`.* TO 'acme-user'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, 
    CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, CREATE ROUTINE, 
    ALTER ROUTINE, EXECUTE, TRIGGER, SHOW VIEW
  ON `Acme-Tender`.* TO 'acme-manager'@'%';
